name: Run Telegram Bot (test run)

on:
  push:
    branches: [main]

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{ 8088511976:AAFeI2M1r6q7d-ALe6TUNX2GFQsE0dS4mi0.BOT_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify telegram installed
        run: python -c "import telegram; import sys; print('python-telegram-bot', getattr(telegram, '__version__', 'unknown')); sys.exit(0)"

      - name: Run bot
        run: python app.py
